services:
  postgres:
    image: pgvector/pgvector:pg15  # Образ с предустановленным pgvector
    container_name: knowledge_base_postgres
    environment:
      POSTGRES_DB: knowledge_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Docker Compose автоматически определит платформу
    image: knowledge-base-app:latest
    container_name: knowledge_base_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/knowledge_base
      DB_USER: postgres
      DB_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test_key}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: