version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: knowledge_base_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: knowledge_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: ghcr.io/vireal01/personal_assistant-api:latest
    container_name: knowledge_base_api
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  bot:
    image: ghcr.io/vireal01/personal_assistant-bot:latest
    container_name: knowledge_base_bot
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: